apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-tutorial
  labels:
    app: k8s-tutorial
    name: k8s-tutorial
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: k8s-tutorial
        name: k8s-tutorial
    spec:
      imagePullSecrets:
        - name: registry
      containers:
        - name: k8s-tutorial
          image: vidbina/k8stutorial:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: mysecret
              mountPath: /tmp/mysecret
              readOnly: true
      volumes:
      - name: mysecret
        secret:
          secretName: k8stutorial-secret
