apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-tut-vidbina
  labels:
    app: k8s-tut-vidbina
    name: k8s-tut-vidbina
    owner: vidbina
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-tut-vidbina
        name: k8s-tut-vidbina
    spec:
      imagePullSecrets:
        - name: registry
      containers:
        - name: k8s-tut-vidbina
          image: mobilityhouse/k8s-tut-vidbina:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: mysecret
              mountPath: /tmp/mysecret
              readOnly: true
      volumes:
      - name: mysecret
        secret:
          secretName: k8s-tut-secret
