apiVersion: v1
kind: Service
metadata:
  name: k8s-tut-vidbina
  annotations:
    romulus/host: 'tutvidbina.zeta.tmh.io'
    romulus/path: '/'
  labels:
    name: k8s-tut-vidbina
    romulus/type: external
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: k8s-tut-vidbina
